-- Performance by case and by bank. Additive: new tables and views only.
-- Run this FIRST, then run migration_cases_data.sql (generated by tools/case_map.py).
-- Existing views and the objective tab are untouched.

-- Which learning objectives belong to which case. Matched to the app's topics
-- by name ('Objective <code>'), so it also applies to banks uploaded later.
create table if not exists public.cases (
  number integer primary key,
  title  text not null default ''
);

create table if not exists public.case_objectives (
  case_number integer not null references public.cases(number) on delete cascade,
  code        text    not null,
  primary key (case_number, code)
);

-- No direct client access; the views below (owned by the database) read them.
alter table public.cases enable row level security;
alter table public.case_objectives enable row level security;

-- By bank, oldest upload first. "answered" counts a question the same way the
-- objective view does, so the numbers agree across tabs.
create or replace view public.v_my_bank_performance as
  select b.slug,
         b.title as bank,
         count(*) as answered,
         count(*) filter (where s.last_result = 'correct') as correct,
         round(100.0 * count(*) filter (where s.last_result = 'correct')
               / nullif(count(*), 0), 1) as pct,
         (select count(*) from questions q2
           where q2.qbank_id = b.id and not q2.is_retired) as total
    from question_status s
    join questions q on q.id = s.question_id
    join qbanks b on b.id = q.qbank_id
   where s.user_id = auth.uid()
     and b.is_published
   group by b.id, b.slug, b.title, b.created_at
   order by b.created_at;

-- By case. A question counts toward every case its objective belongs to.
create or replace view public.v_my_case_performance as
  select c.number as case_number,
         c.title,
         count(*) as answered,
         count(*) filter (where s.last_result = 'correct') as correct,
         round(100.0 * count(*) filter (where s.last_result = 'correct')
               / nullif(count(*), 0), 1) as pct
    from question_status s
    join questions q on q.id = s.question_id
    join topics t on t.id = q.topic_id
    join case_objectives co on 'Objective ' || co.code = t.name
    join cases c on c.number = co.case_number
   where s.user_id = auth.uid()
   group by c.number, c.title
   order by c.number;

-- The objectives inside each case, for the expandable rows.
create or replace view public.v_my_case_objective_performance as
  select c.number as case_number,
         t.name as topic,
         t.description,
         count(*) as answered,
         count(*) filter (where s.last_result = 'correct') as correct,
         round(100.0 * count(*) filter (where s.last_result = 'correct')
               / nullif(count(*), 0), 1) as pct
    from question_status s
    join questions q on q.id = s.question_id
    join topics t on t.id = q.topic_id
    join case_objectives co on 'Objective ' || co.code = t.name
    join cases c on c.number = co.case_number
   where s.user_id = auth.uid()
   group by c.number, t.name, t.description
   order by c.number, pct nulls last, t.name;

grant select on public.v_my_bank_performance to authenticated;
grant select on public.v_my_case_performance to authenticated;
grant select on public.v_my_case_objective_performance to authenticated;
