#!/usr/bin/env python3
"""
case_map.py — turn the Wellness case learning-objective spreadsheets into SQL.

    python tools\\case_map.py "C:\\path\\to\\Wellness_Case_5_....xlsx" "...Case_6_....xlsx" ...

Writes migrations\\migration_cases_data.sql (or --out): paste it into the
Supabase SQL Editor. Safe to re-run — it only adds or updates, so when a new
case's spreadsheet is released, run this again with ALL the case files.

Each spreadsheet needs a "Case" column (e.g. "05-Wellness Emma Wilson, Well
Infant (Case 5)") and a "Session Objective #" column. Rows whose case has no
number (e.g. "Wellness-No Specific Case") are skipped.

No third-party packages needed.
"""

import argparse
import collections
import pathlib
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"


def _col(ref):
    n = 0
    for ch in re.match(r"[A-Z]+", ref).group(0):
        n = n * 26 + ord(ch) - 64
    return n - 1


def read_sheets(path):
    z = zipfile.ZipFile(path)
    shared = []
    if "xl/sharedStrings.xml" in z.namelist():
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall(f"{{{NS}}}si"):
            shared.append("".join(t.text or "" for t in si.iter(f"{{{NS}}}t")))
    wb = ET.fromstring(z.read("xl/workbook.xml"))
    rels = {r.get("Id"): r.get("Target")
            for r in ET.fromstring(z.read("xl/_rels/workbook.xml.rels"))}
    for sh in wb.find(f"{{{NS}}}sheets"):
        target = rels[sh.get(f"{{{REL}}}id")].lstrip("/")
        if not target.startswith("xl/"):
            target = "xl/" + target
        rows = []
        for row in ET.fromstring(z.read(target)).iter(f"{{{NS}}}row"):
            cells = {}
            for c in row.findall(f"{{{NS}}}c"):
                v = c.find(f"{{{NS}}}v")
                t = c.get("t")
                if t == "s" and v is not None:
                    val = shared[int(v.text)]
                elif t == "inlineStr":
                    val = "".join(x.text or "" for x in c.iter(f"{{{NS}}}t"))
                else:
                    val = v.text if v is not None else None
                cells[_col(c.get("r"))] = val
            if cells:
                rows.append([cells.get(i) for i in range(max(cells) + 1)])
        yield rows


def esc(t):
    return "'" + str(t).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("files", nargs="+", help="case learning-objective .xlsx files")
    ap.add_argument("--out", default="migrations/migration_cases_data.sql")
    args = ap.parse_args()

    titles = {}
    pairs = collections.defaultdict(set)   # case number -> objective codes
    skipped = 0
    for f in args.files:
        for rows in read_sheets(f):
            if not rows or "Case" not in rows[0] or "Session Objective #" not in rows[0]:
                continue
            head = rows[0]
            ci, oi = head.index("Case"), head.index("Session Objective #")
            for r in rows[1:]:
                r = r + [None] * (len(head) - len(r))
                case, code = (r[ci] or "").strip(), (r[oi] or "").strip()
                if not code:
                    continue
                m = re.search(r"\(Case\s*(\d+)\)", case)
                if not m:
                    skipped += 1
                    continue
                n = int(m.group(1))
                pairs[n].add(code)
                t = re.match(r"\d+-Wellness\s+(.*?)\s*\(Case", case)
                if t:
                    titles[n] = t.group(1)

    if not pairs:
        sys.exit("No case/objective rows found. Check the spreadsheets' column names.")

    out = [
        "-- Case -> objective mapping, generated by tools/case_map.py",
        "-- Safe to re-run: it only adds or updates.",
        "begin;",
    ]
    for n in sorted(pairs):
        out.append(
            f"insert into cases (number, title) values ({n}, {esc(titles.get(n, ''))}) "
            "on conflict (number) do update set title = excluded.title;")
    out.append("")
    for n in sorted(pairs):
        codes = sorted(pairs[n])
        out.append(f"-- Case {n}: {len(codes)} objectives")
        out.append("insert into case_objectives (case_number, code) values")
        out.append(",\n".join(f"  ({n}, {esc(c)})" for c in codes))
        out.append("on conflict do nothing;")
        out.append("")
    out.append("commit;")

    path = pathlib.Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    for n in sorted(pairs):
        print(f"Case {n}: {len(pairs[n]):3d} objectives  {titles.get(n, '')}")
    if skipped:
        print(f"({skipped} rows skipped: no case number)")
    print(f"\nwrote {path}")


if __name__ == "__main__":
    main()
